### ISSUE TITLE
The role of the "channel"

### ISSUE THREAD

**Issue by yuriFish** [yoheikikuta/senet-keras#7]
This project is very useful to me, thank you very much. But can you tell me what is the role of the "channel" in line 136 of the SEResNeXt.py file? The object "channel" appears only once in the entire file.

**Comment by yoheikikuta** [comment]
@yuriFish Thanks for your report!
Ah, it's a probably meaningless variable.
I would be appreciated if you sent a PR to me after you check that removing the variable does not affect the model (if possible).

**Comment by yoheikikuta** [comment]
Fixed: https://github.com/yoheikikuta/senet-keras/commit/5cd88fa39baea74de5236301efc249b5d0775f57
